# Generated by Django 3.1.7 on 2021-03-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_group_inserted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_inserted',
            new_name='group',
        ),
    ]
