# Generated by Django 3.1.7 on 2021-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('difficulty', models.CharField(max_length=150)),
                ('frequency', models.CharField(max_length=150)),
                ('achieved', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
