# Generated by Django 3.1.7 on 2021-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='achieved',
            field=models.IntegerField(),
        ),
    ]
