# Generated by Django 3.1.7 on 2021-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20210305_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='how_much_achieved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
    ]
