# Generated by Django 3.1.7 on 2021-06-04 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_on_group',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
